spring.application.name=RunningBack

spring.datasource.url=jdbc:mysql://localhost:3306/runningdb
spring.datasource.username = rlopezbarbarin
spring.datasource.password = 2WHsVzMZjvPi
spring.jpa.hibernate.ddl-auto = update

